### ISSUE TITLE
Apply Material theme to Style Guide

### ISSUE THREAD

**Issue by ContentBrewmaster** [CivicActions/style-guide#7]
**User Story**
As a CivicActions employee, I need a consistent experience when I transition from the guidebook to the style guide so that it's easy for me to find the content I need.

**Acceptance criteria**

- [x] Material theme applied to Style Guide
- [x] Navigation configured in settings
- [x] Preview reviewed by Marketing
- [x] New theme merged

**Comment by ContentBrewmaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apply material theme to style guide](https://trello.com/c/wCDu9GFQ/282-apply-material-theme-to-style-guide)

**Comment by dmundra** [comment]
@grugnog when you get a chance can you give me access to https://readthedocs.org/projects/civicactions-style-guide/?

**Comment by dmundra** [comment]
@ContentBrewmaster here is the preview of the style guide with the material theme: https://civicactions-style-guide.readthedocs.io/en/material/
